// This file is part of the CataCraft project, which is published under the MIT license.

namespace CataCraft.Core.Enums;

public enum ResponseCodes : byte
{
    ResponseSuccess         = 0,
    ResponseFailure         = 1,
    ResponseCancelled       = 2,
    ResponseDisconnected    = 3,
    ResponseFailedToConnect = 4,
    ResponseConnected       = 5,
    ResponseVersionMismatch = 6,

    CstatusConnecting          = 7,
    CstatusNegotiatingSecurity = 8,
    CstatusNegotiationComplete = 9,
    CstatusNegotiationFailed   = 10,
    CstatusAuthenticating      = 11,

    AuthOk                  = 12,
    AuthFailed              = 13,
    AuthReject              = 14,
    AuthBadServerProof      = 15,
    AuthUnavailable         = 16,
    AuthSystemError         = 17,
    AuthBillingError        = 18,
    AuthBillingExpired      = 19,
    AuthVersionMismatch     = 20,
    AuthUnknownAccount      = 21,
    AuthIncorrectPassword   = 22,
    AuthSessionExpired      = 23,
    AuthServerShuttingDown  = 24,
    AuthAlreadyLoggingIn    = 25,
    AuthLoginServerNotFound = 26,
    AuthWaitQueue           = 27,
    AuthBanned              = 28,
    AuthAlreadyOnline       = 29,
    AuthNoTime              = 30,
    AuthDbBusy              = 31,
    AuthSuspended           = 32,
    AuthParentalControl     = 33,
    AuthLockedEnforced      = 34,

    RealmListInProgress    = 35,
    RealmListSuccess       = 36,
    RealmListFailed        = 37,
    RealmListInvalid       = 38,
    RealmListRealmNotFound = 39,

    AccountCreateInProgress = 40,
    AccountCreateSuccess    = 41,
    AccountCreateFailed     = 42,

    CharListRetrieving = 43,
    CharListRetrieved  = 44,
    CharListFailed     = 45,

    CharCreateInProgress           = 46,
    CharCreateSuccess              = 47,
    CharCreateError                = 48,
    CharCreateFailed               = 49,
    CharCreateNameInUse            = 50,
    CharCreateDisabled             = 51,
    CharCreatePvpTeamsViolation    = 52,
    CharCreateServerLimit          = 53,
    CharCreateAccountLimit         = 54,
    CharCreateServerQueue          = 55,
    CharCreateOnlyExisting         = 56,
    CharCreateExpansion            = 57,
    CharCreateExpansionClass       = 58,
    CharCreateLevelRequirement     = 59,
    CharCreateUniqueClassLimit     = 60,
    CharCreateCharacterInGuild     = 61,
    CharCreateRestrictedRaceclass  = 62,
    CharCreateCharacterChooseRace  = 63,
    CharCreateCharacterArenaLeader = 64,
    CharCreateCharacterDeleteMail  = 65,
    CharCreateCharacterSwapFaction = 66,
    CharCreateCharacterRaceOnly    = 67,
    CharCreateCharacterGoldLimit   = 68,
    CharCreateForceLogin           = 69,

    CharDeleteInProgress              = 70,
    CharDeleteSuccess                 = 71,
    CharDeleteFailed                  = 72,
    CharDeleteFailedLockedForTransfer = 73,
    CharDeleteFailedGuildLeader       = 74,
    CharDeleteFailedArenaCaptain      = 75,
    CharDeleteFailedHasHeirloomOrMail = 76,

    CharLoginInProgress         = 77,
    CharLoginSuccess            = 78,
    CharLoginNoWorld            = 79,
    CharLoginDuplicateCharacter = 80,
    CharLoginNoInstances        = 81,
    CharLoginFailed             = 82,
    CharLoginDisabled           = 83,
    CharLoginNoCharacter        = 84,
    CharLoginLockedForTransfer  = 85,
    CharLoginLockedByBilling    = 86,
    CharLoginLockedByMobileAh   = 87,
    CharLoginTemporaryGmLock    = 88,

    CharNameSuccess                                = 89,
    CharNameFailure                                = 90,
    CharNameNoName                                 = 91,
    CharNameTooShort                               = 92,
    CharNameTooLong                                = 93,
    CharNameInvalidCharacter                       = 94,
    CharNameMixedLanguages                         = 95,
    CharNameProfane                                = 96,
    CharNameReserved                               = 97,
    CharNameInvalidApostrophe                      = 98,
    CharNameMultipleApostrophes                    = 99,
    CharNameThreeConsecutive                       = 100,
    CharNameInvalidSpace                           = 101,
    CharNameConsecutiveSpaces                      = 102,
    CharNameRussianConsecutiveSilentCharacters     = 103,
    CharNameRussianSilentCharacterAtBeginningOrEnd = 104,
    CharNameDeclensionDoesntMatchBaseName          = 105
}
