// This file is part of the CataCraft project, which is published under the MIT license.

using System.Reflection;
using CataCraft.Configuration;
using CataCraft.DBC.Attributes;
using CataCraft.DBC.Model;
using DBCD.IO;

namespace CataCraft.DBC;

public static class DBCManager
{
    public static Dictionary<int, DestructibleModelDataEntry> SDestructibleModelDataStore { get; private set; } = [];
    public static Dictionary<int, gtOCTBaseHPByClassEntry> SgtOCTBaseHPByClassStore { get; private set; } = [];
    public static Dictionary<int, AttackAnimTypesEntry> SAttackAnimTypesStore { get; private set; } = [];
    public static Dictionary<int, SpellFlyoutItemEntry> SSpellFlyoutItemStore { get; private set; } = [];
    public static Dictionary<int, TaxiNodesEntry> STaxiNodesStore { get; private set; } = [];
    public static Dictionary<int, FootstepTerrainLookupEntry> SFootstepTerrainLookupStore { get; private set; } = [];
    public static Dictionary<int, LightFloatBandEntry> SLightFloatBandStore { get; private set; } = [];
    public static Dictionary<int, ItemCurrencyCostEntry> SItemCurrencyCostStore { get; private set; } = [];
    public static Dictionary<int, TransportPhysicsEntry> STransportPhysicsStore { get; private set; } = [];
    public static Dictionary<int, SpellCastingRequirementsEntry> SSpellCastingRequirementsStore { get; private set; } = [];
    public static Dictionary<int, StationeryEntry> SStationeryStore { get; private set; } = [];
    public static Dictionary<int, VideoHardwareEntry> SVideoHardwareStore { get; private set; } = [];
    public static Dictionary<int, CfgCategoriesEntry> SCfgCategoriesStore { get; private set; } = [];
    public static Dictionary<int, TaxiPathEntry> STaxiPathStore { get; private set; } = [];
    public static Dictionary<int, FactionTemplateEntry> SFactionTemplateStore { get; private set; } = [];
    public static Dictionary<int, WeaponImpactSoundsEntry> SWeaponImpactSoundsStore { get; private set; } = [];
    public static Dictionary<int, ItemRandomPropertiesEntry> SItemRandomPropertiesStore { get; private set; } = [];
    public static Dictionary<int, SpellTargetRestrictionsEntry> SSpellTargetRestrictionsStore { get; private set; } = [];
    public static Dictionary<int, LiquidMaterialEntry> SLiquidMaterialStore { get; private set; } = [];
    public static Dictionary<int, TerrainMaterialEntry> STerrainMaterialStore { get; private set; } = [];
    public static Dictionary<int, AnimReplacementSetEntry> SAnimReplacementSetStore { get; private set; } = [];
    public static Dictionary<int, SoundEntriesAdvancedEntry> SSoundEntriesAdvancedStore { get; private set; } = [];
    public static Dictionary<int, gtChanceToMeleeCritEntry> SgtChanceToMeleeCritStore { get; private set; } = [];
    public static Dictionary<int, SoundFilterElemEntry> SSoundFilterElemStore { get; private set; } = [];
    public static Dictionary<int, SpellAuraRestrictionsEntry> SSpellAuraRestrictionsStore { get; private set; } = [];
    public static Dictionary<int, CreatureDisplayInfoExtraEntry> SCreatureDisplayInfoExtraStore { get; private set; } = [];
    public static Dictionary<int, SpellVisualKitEntry> SSpellVisualKitStore { get; private set; } = [];
    public static Dictionary<int, ItemDamageAmmoEntry> SItemDamageAmmoStore { get; private set; } = [];
    public static Dictionary<int, ItemDisplayInfoEntry> SItemDisplayInfoStore { get; private set; } = [];
    public static Dictionary<int, ItemDamageRangedEntry> SItemDamageRangedStore { get; private set; } = [];
    public static Dictionary<int, SpellVisualPrecastTransitionsEntry> SSpellVisualPrecastTransitionsStore { get; private set; } = [];
    public static Dictionary<int, ResearchBranchEntry> SResearchBranchStore { get; private set; } = [];
    public static Dictionary<int, LFGDungeonsGroupingMapEntry> SLfgDungeonsGroupingMapStore { get; private set; } = [];
    public static Dictionary<int, ItemDamageTwoHandEntry> SItemDamageTwoHandStore { get; private set; } = [];
    public static Dictionary<int, SpellItemEnchantmentEntry> SSpellItemEnchantmentStore { get; private set; } = [];
    public static Dictionary<int, AnimKitConfigBoneSetEntry> SAnimKitConfigBoneSetStore { get; private set; } = [];
    public static Dictionary<int, ItemGroupSoundsEntry> SItemGroupSoundsStore { get; private set; } = [];
    public static Dictionary<int, ResearchProjectEntry> SResearchProjectStore { get; private set; } = [];
    public static Dictionary<int, ImportPriceQualityEntry> SImportPriceQualityStore { get; private set; } = [];
    public static Dictionary<int, CastableRaidBuffsEntry> SCastableRaidBuffsStore { get; private set; } = [];
    public static Dictionary<int, SpellAuraVisibilityEntry> SSpellAuraVisibilityStore { get; private set; } = [];
    public static Dictionary<int, ItemRandomSuffixEntry> SItemRandomSuffixStore { get; private set; } = [];
    public static Dictionary<int, GlyphPropertiesEntry> SGlyphPropertiesStore { get; private set; } = [];
    public static Dictionary<int, HolidayNamesEntry> SHolidayNamesStore { get; private set; } = [];
    public static Dictionary<int, gtOCTClassCombatRatingScalarEntry> SgtOCTClassCombatRatingScalarStore { get; private set; } = [];
    public static Dictionary<int, LanguageWordsEntry> SLanguageWordsStore { get; private set; } = [];
    public static Dictionary<int, FactionEntry> SFactionStore { get; private set; } = [];
    public static Dictionary<int, DungeonEncounterEntry> SDungeonEncounterStore { get; private set; } = [];
    public static Dictionary<int, FactionGroupEntry> SFactionGroupStore { get; private set; } = [];
    public static Dictionary<int, SpellRuneCostEntry> SSpellRuneCostStore { get; private set; } = [];
    public static Dictionary<int, AnimReplacementEntry> SAnimReplacementStore { get; private set; } = [];
    public static Dictionary<int, PhaseShiftZoneSoundsEntry> SPhaseShiftZoneSoundsStore { get; private set; } = [];
    public static Dictionary<int, ResearchSiteEntry> SResearchSiteStore { get; private set; } = [];
    public static Dictionary<int, QuestSortEntry> SQuestSortStore { get; private set; } = [];
    public static Dictionary<int, PlayerConditionEntry> SPlayerConditionStore { get; private set; } = [];
    public static Dictionary<int, gtChanceToSpellCritBaseEntry> SgtChanceToSpellCritBaseStore { get; private set; } = [];
    public static Dictionary<int, SpellAuraOptionsEntry> SSpellAuraOptionsStore { get; private set; } = [];
    public static Dictionary<int, gtOCTBaseMPByClassEntry> SgtOCTBaseMPByClassStore { get; private set; } = [];
    public static Dictionary<int, LoadingScreensEntry> SLoadingScreensStore { get; private set; } = [];
    public static Dictionary<int, LockTypeEntry> SLockTypeStore { get; private set; } = [];
    public static Dictionary<int, TotemCategoryEntry> STotemCategoryStore { get; private set; } = [];
    public static Dictionary<int, WMOAreaTableEntry> SWMOAreaTableStore { get; private set; } = [];
    public static Dictionary<int, gtOCTRegenMPEntry> SgtOCTRegenMPStore { get; private set; } = [];
    public static Dictionary<int, ResistancesEntry> SResistancesStore { get; private set; } = [];
    public static Dictionary<int, VehicleUIIndSeatEntry> SVehicleUIIndSeatStore { get; private set; } = [];
    public static Dictionary<int, StartupStringsEntry> SStartupStringsStore { get; private set; } = [];
    public static Dictionary<int, SpellDescriptionVariablesEntry> SSpellDescriptionVariablesStore { get; private set; } = [];
    public static Dictionary<int, SpellCooldownsEntry> SSpellCooldownsStore { get; private set; } = [];
    public static Dictionary<int, ObjectEffectPackageElemEntry> SObjectEffectPackageElemStore { get; private set; } = [];
    public static Dictionary<int, ItemSetEntry> SItemSetStore { get; private set; } = [];
    public static Dictionary<int, ImportPriceArmorEntry> SImportPriceArmorStore { get; private set; } = [];
    public static Dictionary<int, CfgConfigsEntry> SCfgConfigsStore { get; private set; } = [];
    public static Dictionary<int, JournalEncounterCreatureEntry> SJournalEncounterCreatureStore { get; private set; } = [];
    public static Dictionary<int, ItemEntry> SItemStore { get; private set; } = [];
    public static Dictionary<int, AreaPOISortedWorldStateEntry> SAreaPOISortedWorldStateStore { get; private set; } = [];
    public static Dictionary<int, SoundEmittersEntry> SSoundEmittersStore { get; private set; } = [];
    public static Dictionary<int, MovieVariationEntry> SMovieVariationStore { get; private set; } = [];
    public static Dictionary<int, SpellVisualEffectNameEntry> SSpellVisualEffectNameStore { get; private set; } = [];
    public static Dictionary<int, GemPropertiesEntry> SGemPropertiesStore { get; private set; } = [];
    public static Dictionary<int, GameTipsEntry> SGameTipsStore { get; private set; } = [];
    public static Dictionary<int, WorldPVPAreaEntry> SWorldPVPAreaStore { get; private set; } = [];
    public static Dictionary<int, SpellCastTimesEntry> SSpellCastTimesStore { get; private set; } = [];
    public static Dictionary<int, TransportRotationEntry> STransportRotationStore { get; private set; } = [];
    public static Dictionary<int, UnitBloodLevelsEntry> SUnitBloodLevelsStore { get; private set; } = [];
    public static Dictionary<int, NamesProfanityEntry> SNamesProfanityStore { get; private set; } = [];
    public static Dictionary<int, ItemLimitCategoryEntry> SItemLimitCategoryStore { get; private set; } = [];
    public static Dictionary<int, CurrencyTypesEntry> SCurrencyTypesStore { get; private set; } = [];
    public static Dictionary<int, SoundEmitterPillPointsEntry> SSoundEmitterPillPointsStore { get; private set; } = [];
    public static Dictionary<int, LFGDungeonGroupEntry> SLFGDungeonGroupStore { get; private set; } = [];
    public static Dictionary<int, AchievementCategoryEntry> SAchievementCategoryStore { get; private set; } = [];
    public static Dictionary<int, SkillLineAbilitySortedSpellEntry> SSkillLineAbilitySortedSpellStore { get; private set; } = [];
    public static Dictionary<int, CreatureFamilyEntry> SCreatureFamilyStore { get; private set; } = [];
    public static Dictionary<int, JournalEncounterSectionEntry> SJournalEncounterSectionStore { get; private set; } = [];
    public static Dictionary<int, ItemArmorShieldEntry> SItemArmorShieldStore { get; private set; } = [];
    public static Dictionary<int, StringLookupsEntry> SStringLookupsStore { get; private set; } = [];
    public static Dictionary<int, SpellReagentsEntry> SSpellReagentsStore { get; private set; } = [];
    public static Dictionary<int, ScalingStatDistributionEntry> SScalingStatDistributionStore { get; private set; } = [];
    public static Dictionary<int, EmotesEntry> SEmotesStore { get; private set; } = [];
    public static Dictionary<int, JournalInstanceEntry> SJournalInstanceStore { get; private set; } = [];
    public static Dictionary<int, ItemVisualsEntry> SItemVisualsStore { get; private set; } = [];
    public static Dictionary<int, VocalUISoundsEntry> SVocalUISoundsStore { get; private set; } = [];
    public static Dictionary<int, ChatProfanityEntry> SChatProfanityStore { get; private set; } = [];
    public static Dictionary<int, LightIntBandEntry> SLightIntBandStore { get; private set; } = [];
    public static Dictionary<int, GuildColorBorderEntry> SGuildColorBorderStore { get; private set; } = [];
    public static Dictionary<int, gtNPCManaCostScalerEntry> SgtNPCManaCostScalerStore { get; private set; } = [];
    public static Dictionary<int, ImportPriceWeaponEntry> SImportPriceWeaponStore { get; private set; } = [];
    public static Dictionary<int, BannedAddonsEntry> SBannedAddonsStore { get; private set; } = [];
    public static Dictionary<int, VehicleEntry> SVehicleStore { get; private set; } = [];
    public static Dictionary<int, ZoneIntroMusicTableEntry> SZoneIntroMusicTableStore { get; private set; } = [];
    public static Dictionary<int, ItemDamageOneHandEntry> SItemDamageOneHandStore { get; private set; } = [];
    public static Dictionary<int, ItemArmorQualityEntry> SItemArmorQualityStore { get; private set; } = [];
    public static Dictionary<int, SoundFilterEntry> SSoundFilterStore { get; private set; } = [];
    public static Dictionary<int, ItemClassEntry> SItemClassStore { get; private set; } = [];
    public static Dictionary<int, SpellChainEffectsEntry> SSpellChainEffectsStore { get; private set; } = [];
    public static Dictionary<int, SpellEffectEntry> SSpellEffectStore { get; private set; } = [];
    public static Dictionary<int, ItemReforgeEntry> SItemReforgeStore { get; private set; } = [];
    public static Dictionary<int, ChrRacesEntry> SChrRacesStore { get; private set; } = [];
    public static Dictionary<int, SpellDifficultyEntry> SSpellDifficultyStore { get; private set; } = [];
    public static Dictionary<int, AnimationDataEntry> SAnimationDataStore { get; private set; } = [];
    public static Dictionary<int, GameObjectArtKitEntry> SGameObjectArtKitStore { get; private set; } = [];
    public static Dictionary<int, QuestFactionRewardEntry> SQuestFactionRewardStore { get; private set; } = [];
    public static Dictionary<int, WowErrorStringsEntry> SWowErrorStringsStore { get; private set; } = [];
    public static Dictionary<int, ItemExtendedCostEntry> SItemExtendedCostStore { get; private set; } = [];
    public static Dictionary<int, ScreenEffectEntry> SScreenEffectStore { get; private set; } = [];
    public static Dictionary<int, ExhaustionEntry> SExhaustionStore { get; private set; } = [];
    public static Dictionary<int, LFGDungeonExpansionEntry> SLFGDungeonExpansionStore { get; private set; } = [];
    public static Dictionary<int, GMSurveyAnswersEntry> SGMSurveyAnswersStore { get; private set; } = [];
    public static Dictionary<int, CreatureDisplayInfoEntry> SCreatureDisplayInfoStore { get; private set; } = [];
    public static Dictionary<int, SpellSpecialUnitEffectEntry> SSpellSpecialUnitEffectStore { get; private set; } = [];
    public static Dictionary<int, WorldStateZoneSoundsEntry> SWorldStateZoneSoundsStore { get; private set; } = [];
    public static Dictionary<int, MovieEntry> SMovieStore { get; private set; } = [];
    public static Dictionary<int, LanguagesEntry> SLanguagesStore { get; private set; } = [];
    public static Dictionary<int, NPCSoundsEntry> SNPCSoundsStore { get; private set; } = [];
    public static Dictionary<int, gtSpellScalingEntry> SgtSpellScalingStore { get; private set; } = [];
    public static Dictionary<int, TalentTabEntry> STalentTabStore { get; private set; } = [];
    public static Dictionary<int, ItemPriceBaseEntry> SItemPriceBaseStore { get; private set; } = [];
    public static Dictionary<int, ObjectEffectModifierEntry> SObjectEffectModifierStore { get; private set; } = [];
    public static Dictionary<int, AreaPOIEntry> SAreaPOIStore { get; private set; } = [];
    public static Dictionary<int, SpellActivationOverlayEntry> SSpellActivationOverlayStore { get; private set; } = [];
    public static Dictionary<int, ItemArmorTotalEntry> SItemArmorTotalStore { get; private set; } = [];
    public static Dictionary<int, ItemDamageTwoHandCasterEntry> SItemDamageTwoHandCasterStore { get; private set; } = [];
    public static Dictionary<int, DeclinedWordEntry> SDeclinedWordStore { get; private set; } = [];
    public static Dictionary<int, TalentTreePrimarySpellsEntry> STalentTreePrimarySpellsStore { get; private set; } = [];
    public static Dictionary<int, SoundAmbienceFlavorEntry> SSoundAmbienceFlavorStore { get; private set; } = [];
    public static Dictionary<int, LiquidObjectEntry> SLiquidObjectStore { get; private set; } = [];
    public static Dictionary<int, JournalEncounterItemEntry> SJournalEncounterItemStore { get; private set; } = [];
    public static Dictionary<int, TerrainTypeSoundsEntry> STerrainTypeSoundsStore { get; private set; } = [];
    public static Dictionary<int, gtOCTHpPerStaminaEntry> SgtOCTHpPerStaminaStore { get; private set; } = [];
    public static Dictionary<int, MailTemplateEntry> SMailTemplateStore { get; private set; } = [];
    public static Dictionary<int, DurabilityCostsEntry> SDurabilityCostsStore { get; private set; } = [];
    public static Dictionary<int, BankBagSlotPricesEntry> SBankBagSlotPricesStore { get; private set; } = [];
    public static Dictionary<int, AreaTableEntry> SAreaTableStore { get; private set; } = [];
    public static Dictionary<int, EmotesTextDataEntry> SEmotesTextDataStore { get; private set; } = [];
    public static Dictionary<int, TaxiPathNodeEntry> STaxiPathNodeStore { get; private set; } = [];
    public static Dictionary<int, GMSurveyCurrentSurveyEntry> SGMSurveyCurrentSurveyStore { get; private set; } = [];
    public static Dictionary<int, SpellEntry> SSpellStore { get; private set; } = [];
    public static Dictionary<int, VehicleUIIndicatorEntry> SVehicleUIIndicatorStore { get; private set; } = [];
    public static Dictionary<int, ChatChannelsEntry> SChatChannelsStore { get; private set; } = [];
    public static Dictionary<int, AnimKitEntry> SAnimKitStore { get; private set; } = [];
    public static Dictionary<int, RandPropPointsEntry> SRandPropPointsStore { get; private set; } = [];
    public static Dictionary<int, SpellIconEntry> SSpellIconStore { get; private set; } = [];
    public static Dictionary<int, ObjectEffectPackageEntry> SObjectEffectPackageStore { get; private set; } = [];
    public static Dictionary<int, ItemDisenchantLootEntry> SItemDisenchantLootStore { get; private set; } = [];
    public static Dictionary<int, WorldMapAreaEntry> SWorldMapAreaStore { get; private set; } = [];
    public static Dictionary<int, LightEntry> SLightStore { get; private set; } = [];
    public static Dictionary<int, ZoneMusicEntry> SZoneMusicStore { get; private set; } = [];
    public static Dictionary<int, BarberShopStyleEntry> SBarberShopStyleStore { get; private set; } = [];
    public static Dictionary<int, QuestPOIBlobEntry> SQuestPOIBlobStore { get; private set; } = [];
    public static Dictionary<int, ChrClassesEntry> SChrClassesStore { get; private set; } = [];
    public static Dictionary<int, ObjectEffectGroupEntry> SObjectEffectGroupStore { get; private set; } = [];
    public static Dictionary<int, FootprintTexturesEntry> SFootprintTexturesStore { get; private set; } = [];
    public static Dictionary<int, WeatherEntry> SWeatherStore { get; private set; } = [];
    public static Dictionary<int, GroundEffectDoodadEntry> SGroundEffectDoodadStore { get; private set; } = [];
    public static Dictionary<int, ItemVisualEffectsEntry> SItemVisualEffectsStore { get; private set; } = [];
    public static Dictionary<int, GameObjectDisplayInfoEntry> SGameObjectDisplayInfoStore { get; private set; } = [];
    public static Dictionary<int, DungeonMapChunkEntry> SDungeonMapChunkStore { get; private set; } = [];
    public static Dictionary<int, ItemDamageOneHandCasterEntry> SItemDamageOneHandCasterStore { get; private set; } = [];
    public static Dictionary<int, SpellShapeshiftFormEntry> SSpellShapeshiftFormStore { get; private set; } = [];
    public static Dictionary<int, HolidayDescriptionsEntry> SHolidayDescriptionsStore { get; private set; } = [];
    public static Dictionary<int, AreaTriggerEntry> SAreaTriggerStore { get; private set; } = [];
    public static Dictionary<int, SpellShapeshiftEntry> SSpellShapeshiftStore { get; private set; } = [];
    public static Dictionary<int, DeclinedWordCasesEntry> SDeclinedWordCasesStore { get; private set; } = [];
    public static Dictionary<int, CameraModeEntry> SCameraModeStore { get; private set; } = [];
    public static Dictionary<int, PowerDisplayEntry> SPowerDisplayStore { get; private set; } = [];
    public static Dictionary<int, SpellMissileEntry> SSpellMissileStore { get; private set; } = [];
    public static Dictionary<int, ItemDamageWandEntry> SItemDamageWandStore { get; private set; } = [];
    public static Dictionary<int, SpellRangeEntry> SSpellRangeStore { get; private set; } = [];
    public static Dictionary<int, SpellLevelsEntry> SSpellLevelsStore { get; private set; } = [];
    public static Dictionary<int, ZoneLightPointEntry> SZoneLightPointStore { get; private set; } = [];
    public static Dictionary<int, DeathThudLookupsEntry> SDeathThudLookupsStore { get; private set; } = [];
    public static Dictionary<int, SkillTiersEntry> SSkillTiersStore { get; private set; } = [];
    public static Dictionary<int, LiquidTypeEntry> SLiquidTypeStore { get; private set; } = [];
    public static Dictionary<int, ItemPetFoodEntry> SItemPetFoodStore { get; private set; } = [];
    public static Dictionary<int, gtRegenMPPerSptEntry> SgtRegenMPPerSptStore { get; private set; } = [];
    public static Dictionary<int, SpamMessagesEntry> SSpamMessagesStore { get; private set; } = [];
    public static Dictionary<int, SpellEffectCameraShakesEntry> SSpellEffectCameraShakesStore { get; private set; } = [];
    public static Dictionary<int, SummonPropertiesEntry> SSummonPropertiesStore { get; private set; } = [];
    public static Dictionary<int, WorldMapOverlayEntry> SWorldMapOverlayStore { get; private set; } = [];
    public static Dictionary<int, VehicleSeatEntry> SVehicleSeatStore { get; private set; } = [];
    public static Dictionary<int, ArmorLocationEntry> SArmorLocationStore { get; private set; } = [];
    public static Dictionary<int, SpellClassOptionsEntry> SSpellClassOptionsStore { get; private set; } = [];
    public static Dictionary<int, PackageEntry> SPackageStore { get; private set; } = [];
    public static Dictionary<int, KeychainEntry> SKeychainStore { get; private set; } = [];
    public static Dictionary<int, EnvironmentalDamageEntry> SEnvironmentalDamageStore { get; private set; } = [];
    public static Dictionary<int, HelmetGeosetVisDataEntry> SHelmetGeosetVisDataStore { get; private set; } = [];
    public static Dictionary<int, CreatureSpellDataEntry> SCreatureSpellDataStore { get; private set; } = [];
    public static Dictionary<int, JournalEncounterEntry> SJournalEncounterStore { get; private set; } = [];
    public static Dictionary<int, EmotesTextSoundEntry> SEmotesTextSoundStore { get; private set; } = [];
    public static Dictionary<int, AchievementEntry> SAchievementStore { get; private set; } = [];
    public static Dictionary<int, MovieFileDataEntry> SMovieFileDataStore { get; private set; } = [];
    public static Dictionary<int, HolidaysEntry> SHolidaysStore { get; private set; } = [];
    public static Dictionary<int, SpellMechanicEntry> SSpellMechanicStore { get; private set; } = [];
    public static Dictionary<int, LightParamsEntry> SLightParamsStore { get; private set; } = [];
    public static Dictionary<int, AnimKitSegmentEntry> SAnimKitSegmentStore { get; private set; } = [];
    public static Dictionary<int, CharTitlesEntry> SCharTitlesStore { get; private set; } = [];
    public static Dictionary<int, AttackAnimKitsEntry> SAttackAnimKitsStore { get; private set; } = [];
    public static Dictionary<int, WorldSafeLocsEntry> SWorldSafeLocsStore { get; private set; } = [];
    public static Dictionary<int, LFGDungeonsEntry> SLFGDungeonsStore { get; private set; } = [];
    public static Dictionary<int, CreatureModelDataEntry> SCreatureModelDataStore { get; private set; } = [];
    public static Dictionary<int, gtChanceToMeleeCritBaseEntry> SgtChanceToMeleeCritBaseStore { get; private set; } = [];
    public static Dictionary<int, BattlemasterListEntry> SBattlemasterListStore { get; private set; } = [];
    public static Dictionary<int, CreatureSoundDataEntry> SCreatureSoundDataStore { get; private set; } = [];
    public static Dictionary<int, LoadingScreenTaxiSplinesEntry> SLoadingScreenTaxiSplinesStore { get; private set; } = [];
    public static Dictionary<int, AchievementCriteriaEntry> SAchievementCriteriaStore { get; private set; } = [];
    public static Dictionary<int, LightSkyboxEntry> SLightSkyboxStore { get; private set; } = [];
    public static Dictionary<int, SoundProviderPreferencesEntry> SSoundProviderPreferencesStore { get; private set; } = [];
    public static Dictionary<int, SoundAmbienceEntry> SSoundAmbienceStore { get; private set; } = [];
    public static Dictionary<int, ParticleColorEntry> SParticleColorStore { get; private set; } = [];
    public static Dictionary<int, GuildColorBackgroundEntry> SGuildColorBackgroundStore { get; private set; } = [];
    public static Dictionary<int, CreatureTypeEntry> SCreatureTypeStore { get; private set; } = [];
    public static Dictionary<int, LockEntry> SLockStore { get; private set; } = [];
    public static Dictionary<int, NameGenEntry> SNameGenStore { get; private set; } = [];
    public static Dictionary<int, SpellEquippedItemsEntry> SSpellEquippedItemsStore { get; private set; } = [];
    public static Dictionary<int, PhaseXPhaseGroupEntry> SPhaseXPhaseGroupStore { get; private set; } = [];
    public static Dictionary<int, CinematicCameraEntry> SCinematicCameraStore { get; private set; } = [];
    public static Dictionary<int, AnimKitBoneSetAliasEntry> SAnimKitBoneSetAliasStore { get; private set; } = [];
    public static Dictionary<int, CharacterFacialHairStylesEntry> SCharacterFacialHairStylesStore { get; private set; } = [];
    public static Dictionary<int, SpellAuraVisXTalentTabEntry> SSpellAuraVisXTalentTabStore { get; private set; } = [];
    public static Dictionary<int, GuildPerkSpellsEntry> SGuildPerkSpellsStore { get; private set; } = [];
    public static Dictionary<int, QuestPOIPointEntry> SQuestPOIPointStore { get; private set; } = [];
    public static Dictionary<int, CharHairGeosetsEntry> SCharHairGeosetsStore { get; private set; } = [];
    public static Dictionary<int, CharStartOutfitEntry> SCharStartOutfitStore { get; private set; } = [];
    public static Dictionary<int, ItemNameDescriptionEntry> SItemNameDescriptionStore { get; private set; } = [];
    public static Dictionary<int, ItemPurchaseGroupEntry> SItemPurchaseGroupStore { get; private set; } = [];
    public static Dictionary<int, UnitBloodEntry> SUnitBloodStore { get; private set; } = [];
    public static Dictionary<int, PageTextMaterialEntry> SPageTextMaterialStore { get; private set; } = [];
    public static Dictionary<int, ImportPriceShieldEntry> SImportPriceShieldStore { get; private set; } = [];
    public static Dictionary<int, QuestInfoEntry> SQuestInfoStore { get; private set; } = [];
    public static Dictionary<int, PaperDollItemFrameEntry> SPaperDollItemFrameStore { get; private set; } = [];
    public static Dictionary<int, MountCapabilityEntry> SMountCapabilityStore { get; private set; } = [];
    public static Dictionary<int, SpellRadiusEntry> SSpellRadiusStore { get; private set; } = [];
    public static Dictionary<int, gtChanceToSpellCritEntry> SgtChanceToSpellCritStore { get; private set; } = [];
    public static Dictionary<int, SkillRaceClassInfoEntry> SSkillRaceClassInfoStore { get; private set; } = [];
    public static Dictionary<int, ResearchFieldEntry> SResearchFieldStore { get; private set; } = [];
    public static Dictionary<int, WorldMapContinentEntry> SWorldMapContinentStore { get; private set; } = [];
    public static Dictionary<int, AuctionHouseEntry> SAuctionHouseStore { get; private set; } = [];
    public static Dictionary<int, SpellCategoryEntry> SSpellCategoryStore { get; private set; } = [];
    public static Dictionary<int, gtBarberShopCostBaseEntry> SgtBarberShopCostBaseStore { get; private set; } = [];
    public static Dictionary<int, ScalingStatValuesEntry> SScalingStatValuesStore { get; private set; } = [];
    public static Dictionary<int, AreaAssignmentEntry> SAreaAssignmentStore { get; private set; } = [];
    public static Dictionary<int, WorldMapTransformsEntry> SWorldMapTransformsStore { get; private set; } = [];
    public static Dictionary<int, NumTalentsAtLevelEntry> SNumTalentsAtLevelStore { get; private set; } = [];
    public static Dictionary<int, SkillLineEntry> SSkillLineStore { get; private set; } = [];
    public static Dictionary<int, FileDataEntry> SFileDataStore { get; private set; } = [];
    public static Dictionary<int, ZoneLightEntry> SZoneLightStore { get; private set; } = [];
    public static Dictionary<int, ItemDamageThrownEntry> SItemDamageThrownStore { get; private set; } = [];
    public static Dictionary<int, AnimKitConfigEntry> SAnimKitConfigStore { get; private set; } = [];
    public static Dictionary<int, SpellFocusObjectEntry> SSpellFocusObjectStore { get; private set; } = [];
    public static Dictionary<int, SpellVisualKitAreaModelEntry> SSpellVisualKitAreaModelStore { get; private set; } = [];
    public static Dictionary<int, TerrainTypeEntry> STerrainTypeStore { get; private set; } = [];
    public static Dictionary<int, DurabilityQualityEntry> SDurabilityQualityStore { get; private set; } = [];
    public static Dictionary<int, AreaGroupEntry> SAreaGroupStore { get; private set; } = [];
    public static Dictionary<int, SpellVisualEntry> SSpellVisualStore { get; private set; } = [];
    public static Dictionary<int, ItemSubClassMaskEntry> SItemSubClassMaskStore { get; private set; } = [];
    public static Dictionary<int, SpellScalingEntry> SSpellScalingStore { get; private set; } = [];
    public static Dictionary<int, ScreenLocationEntry> SScreenLocationStore { get; private set; } = [];
    public static Dictionary<int, PhaseEntry> SPhaseStore { get; private set; } = [];
    public static Dictionary<int, WorldStateUIEntry> SWorldStateUIStore { get; private set; } = [];
    public static Dictionary<int, MapDifficultyEntry> SMapDifficultyStore { get; private set; } = [];
    public static Dictionary<int, SpellCategoriesEntry> SSpellCategoriesStore { get; private set; } = [];
    public static Dictionary<int, MountTypeEntry> SMountTypeStore { get; private set; } = [];
    public static Dictionary<int, DanceMovesEntry> SDanceMovesStore { get; private set; } = [];
    public static Dictionary<int, OverrideSpellDataEntry> SOverrideSpellDataStore { get; private set; } = [];
    public static Dictionary<int, SkillLineCategoryEntry> SSkillLineCategoryStore { get; private set; } = [];
    public static Dictionary<int, GroundEffectTextureEntry> SGroundEffectTextureStore { get; private set; } = [];
    public static Dictionary<int, SpellItemEnchantmentConditionEntry> SSpellItemEnchantmentConditionStore { get; private set; } = [];
    public static Dictionary<int, SpellMissileMotionEntry> SSpellMissileMotionStore { get; private set; } = [];
    public static Dictionary<int, CreatureMovementInfoEntry> SCreatureMovementInfoStore { get; private set; } = [];
    public static Dictionary<int, ChrClassesXPowerTypesEntry> SChrClassesXPowerTypesStore { get; private set; } = [];
    public static Dictionary<int, UnitPowerBarEntry> SUnitPowerBarStore { get; private set; } = [];
    public static Dictionary<int, SpellFlyoutEntry> SSpellFlyoutStore { get; private set; } = [];
    public static Dictionary<int, WeaponSwingSounds2Entry> SWeaponSwingSounds2Store { get; private set; } = [];
    public static Dictionary<int, SpellVisualKitModelAttachEntry> SSpellVisualKitModelAttachStore { get; private set; } = [];
    public static Dictionary<int, SpellPowerEntry> SSpellPowerStore { get; private set; } = [];
    public static Dictionary<int, GuildColorEmblemEntry> SGuildColorEmblemStore { get; private set; } = [];
    public static Dictionary<int, WorldChunkSoundsEntry> SWorldChunkSoundsStore { get; private set; } = [];
    public static Dictionary<int, CreatureImmunitiesEntry> SCreatureImmunitiesStore { get; private set; } = [];
    public static Dictionary<int, ServerMessagesEntry> SServerMessagesStore { get; private set; } = [];
    public static Dictionary<int, GMSurveySurveysEntry> SGMSurveySurveysStore { get; private set; } = [];
    public static Dictionary<int, SpellDurationEntry> SSpellDurationStore { get; private set; } = [];
    public static Dictionary<int, CharSectionsEntry> SCharSectionsStore { get; private set; } = [];
    public static Dictionary<int, SkillLineAbilityEntry> SSkillLineAbilityStore { get; private set; } = [];
    public static Dictionary<int, ItemBagFamilyEntry> SItemBagFamilyStore { get; private set; } = [];
    public static Dictionary<int, CameraShakesEntry> SCameraShakesStore { get; private set; } = [];
    public static Dictionary<int, GlyphSlotEntry> SGlyphSlotStore { get; private set; } = [];
    public static Dictionary<int, SpellInterruptsEntry> SSpellInterruptsStore { get; private set; } = [];
    public static Dictionary<int, SpellTotemsEntry> SSpellTotemsStore { get; private set; } = [];
    public static Dictionary<int, ItemSubClassEntry> SItemSubClassStore { get; private set; } = [];
    public static Dictionary<int, TalentEntry> STalentStore { get; private set; } = [];
    public static Dictionary<int, AnimKitBoneSetEntry> SAnimKitBoneSetStore { get; private set; } = [];
    public static Dictionary<int, gtCombatRatingsEntry> SgtCombatRatingsStore { get; private set; } = [];
    public static Dictionary<int, DungeonMapEntry> SDungeonMapStore { get; private set; } = [];
    public static Dictionary<int, SpellDispelTypeEntry> SSpellDispelTypeStore { get; private set; } = [];
    public static Dictionary<int, GameTablesEntry> SGameTablesStore { get; private set; } = [];
    public static Dictionary<int, QuestXPEntry> SQuestXPStore { get; private set; } = [];
    public static Dictionary<int, CurrencyCategoryEntry> SCurrencyCategoryStore { get; private set; } = [];
    public static Dictionary<int, GMTicketCategoryEntry> SGMTicketCategoryStore { get; private set; } = [];
    public static Dictionary<int, PVPDifficultyEntry> SPVPDifficultyStore { get; private set; } = [];
    public static Dictionary<int, MaterialEntry> SMaterialStore { get; private set; } = [];
    public static Dictionary<int, SoundEntriesFallbacksEntry> SSoundEntriesFallbacksStore { get; private set; } = [];
    public static Dictionary<int, CinematicSequencesEntry> SCinematicSequencesStore { get; private set; } = [];
    public static Dictionary<int, GMSurveyQuestionsEntry> SGMSurveyQuestionsStore { get; private set; } = [];
    public static Dictionary<int, NamesReservedEntry> SNamesReservedStore { get; private set; } = [];
    public static Dictionary<int, GlueScreenEmoteEntry> SGlueScreenEmoteStore { get; private set; } = [];
    public static Dictionary<int, CharBaseInfoEntry> SCharBaseInfoStore { get; private set; } = [];
    public static Dictionary<int, ObjectEffectEntry> SObjectEffectStore { get; private set; } = [];
    public static Dictionary<int, MapEntry> SMapStore { get; private set; } = [];
    public static Dictionary<int, EmotesTextEntry> SEmotesTextStore { get; private set; } = [];
    public static Dictionary<int, SoundEntriesEntry> SSoundEntriesStore { get; private set; } = [];
    public static Dictionary<int, TransportAnimationEntry> STransportAnimationStore { get; private set; } = [];
    public static Dictionary<int, AnimKitPriorityEntry> SAnimKitPriorityStore { get; private set; } = [];

    private static readonly string s_dbcDirectoryPath;

    static DBCManager()
    {
        if (!ConfigManager.TryGetConfigValue("DBCPath", out string? path)
            || !ConfigManager.TryGetConfigValue("DBCLocale", out string? locale))
            throw new Exception("Config values for DBCPath and DBCLocale must be specified.");

        s_dbcDirectoryPath = Path.Combine(path, locale);
    }

    public static void LoadStoragesAsync()
    {
        Console.WriteLine($"Loading DBC storages from path: {s_dbcDirectoryPath}");

        // Select all storage properties from the class
        PropertyInfo[] storageProperties = typeof(DBCManager).GetProperties(BindingFlags.Static | BindingFlags.Public);

        // Initialize each of them multithreaded. This should usually be asynchronous but DBCD does not offer
        // a nice async API for now
        Parallel.ForEach(storageProperties, LoadStorageAsync);

        Console.WriteLine($"Loaded {storageProperties.Length} DBC storages");
    }

    private static void LoadStorageAsync(PropertyInfo storage)
    {
        // Extract the DBC class type from the first generic argument
        Type dbcType = storage.PropertyType.GetGenericArguments()[1];

        // Try to retrieve the db file attribute to figure out its file name
        DBFileAttribute? dbFileAttribute = dbcType.GetCustomAttribute<DBFileAttribute>();
        if (dbFileAttribute == null)
            return;

        string filePath = Path.Combine(s_dbcDirectoryPath, dbFileAttribute.FileName);
        if (!File.Exists(filePath))
            return;

        DBParser parser = new(filePath);
        MethodInfo? methodInfo = typeof(DBParser).GetMethod(nameof(DBParser.PopulateRecords));
        if (methodInfo == null)
            return;

        MethodInfo genericMethod = methodInfo.MakeGenericMethod(dbcType);
        genericMethod.Invoke(parser, [storage.GetValue(null)]);
    }
}
